pipeline {
    agent any

    stages {

        stage('Clone Code') {
            steps {
                git 'https://github.com/Siva290395/mern-backend.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t sivakumar/mern-backend .'
            }
        }

        stage('Push Docker Image') {
            steps {
                withDockerRegistry([ credentialsId: 'dockerhub', url: '' ]) {
                    sh 'docker push sivakumar/mern-backend'
                }
            }
        }

        stage('Deploy Container') {
            steps {
                sh 'docker stop backend || true'
                sh 'docker rm backend || true'
                sh 'docker run -d -p 5000:5000 --name backend sivakumar/mern-backend'
            }
        }

    }
}

